name: Python Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "black<24" pylint
        pip install -r requirements.txt
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0114 -d W1203 -d E1101 -d R0913 -d W0221 --good-names=i,j,ch
    - name: Analyzing the code with black
      run: |
        black --diff --check $(git ls-files '*.py')
